### ISSUE TITLE
addhosts isn't considered  

### ISSUE THREAD

**Issue by tbludau** [redhat-sap/sap-hana-deployment#7] opened 2020-01-19 17:44 UTC
The addhosts Paraemter in the configfile.j2 is very necessary for a Scale-Out Deployment method, but with the last changes it is not possible to add this configuration as a parameter.

With the last known version from my site i used a dynamic parameter which added to the installation method. So it was possible to use features which were not integrated in the template file.

f.e. ./hdblcm --configfile=/tmp/hana_install_{{ item.value.hana_sid|lower}}.cfg -b {{ item.value.hdblcm_params| default('') }}

Take a look in this files:
tasks/hana_deploy.yml
templates/configfile.j2

**Comment by makentenza** [comment] 2020-01-19 22:16
@tbludau when we moved the repo all the original code was cut released so you can use previous version until we do a new one that is working for everyone.

https://github.com/redhat-sap/sap-hana-deployment/tree/v1.0

**Comment by tbludau** [comment] 2020-01-19 22:35
@makentenza i'm using this version at the moment. thanks. But this was something i need for a successfull deployment process in the future for all scenarios

**Comment by makentenza** [comment] 2020-01-22 10:28
@tbludau  Sure, let's add support for Multiple-Host System.

What's the expected format for the `addhosts=` value? Is it comma-separated values like `host2, host3, host4`? From the previous code it looks like only one additional host was accepted.

**Comment by berndfinger** [comment] 2022-01-29 19:28
Closing this issue now because the issue is fixed.

Note: Development and maintenance of this software has stopped.

Its functional scope is covered and expanded by role [sap_hana_install](https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_hana_install).
The role is part of Ansible Collection [sap_install](https://github.com/sap-linuxlab/community.sap_install) in the
GitHub organization [sap-linuxlab](https://github.com/sap-linuxlab), which is a joint initiative by SAP Technology Partners.

**Closed by berndfinger** 2022-01-29 19:28 UTC
